envs:
  global:
    variables:
      oneops.organization: devtools
      oneops.assembly: website
      oneops.environment: prod-concord
      
tools:
  jdk:8
  maven: 3.5.0

flows:
  default:
    - call: checkVersions
    - ./publish.sh
    - oneops.environmentVariableUpdate(platform = 'webserver', component = 'artifact', variables = { SITE_VERSION = '0.0.1-SNAPSHOT' })
    - oneops.environmentCommitAndDeploy(platform = 'webserver')

  checkVersions:
    - (name JDK/Maven version) mvn -v
    - (name Ruby/Gem version) ruby -v; gem -v
    - (name Gem dependencies) gem dependency