envs:
  global:
    variables:
      oneops.organization: devtools
      oneops.assembly: website
      oneops.environment: prod-concord
      
tools:
  jdk:
    - 8
  maven:
    - 3.3.9
  nodejs:
    - 7.7.2
  npm:
    - 4.1.2

flows:
   default:
     - ./publish.sh
     - oneops.environmentVariableUpdate(platform = 'webserver', component = 'artifact', variables = { SITE_VERSION = '0.0.1-SNAPSHOT' })
     - oneops.environmentCommitAndDeploy(platform = 'webserver')

