# ----------------------------------------------------------------------------------------------------------------------
# Site customization
# ----------------------------------------------------------------------------------------------------------------------
# Any variable here is referenced in layouts/pages as {{site.XXX}} so something like {{site.googleId}}
# ----------------------------------------------------------------------------------------------------------------------

id: walmart
name: Concord
domain: concord.walmartlabs.com
url: https://concord.walmartlabs.com
logo: /assets/img/logo.png
description: "Concord is a workflow server."
source_url: https://github.com/walmartlabs/concord-website/tree/master/
crossSite: false
collapseNavDocs: true
display-search-in-header: true
custom-footer: false
contribute: true
edit-on-github: true
matomo-analytics: false
matomo-site-id: 11

concord_source: "https://github.com/walmartlabs/concord/"
concord_plugins_source: "https://github.com/walmartlabs/concord-plugins/"
concord_plugins_version: "0.82.0"
concord_core_version: "1.4.0"
concord_ansible_version: "2.6.10"

navigation:
  - title: DOCS
    url: /docs/index.html
    context: /docs/
  - title: TRAINING
    url: /training.html
    context: /training
  - title: ABOUT
    url: /about.html
    context: /about

defaults:
  -
   scope:
     type: pages
   values:
     permalink: /:path/:basename:output_ext
  -
   scope:
     type: posts
   values:
     permalink: /blog/:year-:month-:day-:title.html

excerpt_separator: <!--more-->


authors:
  ibodrov:
    name: Ivan Bodrov
    web:
  mmoser:
    name: Manfred Moser
    web:


# -------
# Jekyll
# -------
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false

exclude:
  - ".*"
  - "Gemf*"
  - "pom.xml"
  - "*.sh"
  - "wmt-release*"
  - "README.md"
  - "publish.sh"
  - "sonar*"
  - "vendor"
