# ----------------------------------------------------------------------------------------------------------------------
# Site customization
# ----------------------------------------------------------------------------------------------------------------------
# Any variable here is referenced in layouts/pages as {{site.XXX}} so something like {{site.googleId}}
# ----------------------------------------------------------------------------------------------------------------------

id: walmart
name: Concord
domain: concord.walmart.com
url: http://concord.walmart.com
logo: /assets/img/logo.png
description: "Concord is a workflow server."
source_url: https://gecgithub01.walmart.com/devtools/concord-website/tree/master/
crossSite: false
collapseNavDocs: true
display-search-in-header: true
custom-footer: false
contribute: true
edit-on-github: true
matomo-analytics: true
matomo-site-id: 11

concord_source: "https://gecgithub01.walmart.com/devtools/concord/"
concord_plugins_source: "https://gecgithub01.walmart.com/devtools/concord-plugins/"
concord_plugins_version: "0.74.0"
concord_core_version: "0.99.0"
concord_ansible_version: "2.6.7"

navigation:
  - title: DOCS
    url: /docs/index.html
    context: /docs/
  - title: TRAINING
    url: /training.html
    context: /training
  - title: ABOUT
    url: /about.html
    context: /about

defaults:
  -
   scope:
     type: pages
   values:
     permalink: /:path/:basename:output_ext
  -
   scope:
     type: posts
   values:
     permalink: /blog/:year-:month-:day-:title.html

excerpt_separator: <!--more-->


authors:
  team:
    name: The Team
    web: /about
  ibodrov:
    name: Ivan Bodrov
    web: http://sde.walmart.com/about-us.html#ibodrov
  jvanzyl:
    name: Jason van Zyl
    web: http://sde.walmart.com/about-us.html#jvanzyl
  mmoser:
    name: Manfred Moser
    web: http://sde.walmart.com/about-us.html#mmoser


# -------
# Jekyll
# -------
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false

exclude:
  - ".*"
  - "Gemf*"
  - "pom.xml"
  - "*.sh"
  - "wmt-release*"
  - "README.md"
  - "publish.sh"
  - "sonar*"
  - "vendor"

