# ----------------------------------------------------------------------------------------------------------------------
# Site customization
# ----------------------------------------------------------------------------------------------------------------------
# Any variable here is referenced in layouts/pages as {{site.XXX}} so something like {{site.googleId}}
# ----------------------------------------------------------------------------------------------------------------------

id: walmart
name: Concord
domain: concord.prod.walmart.com
url: http://concord.prod.walmart.com
logo: /assets/img/logo.png
description: "Concord is a workflow server."
source_url: https://gecgithub01.walmart.com/devtools/concord-website

navigation:
 - title: ABOUT
   url: /about.html
   context: /about
 - title: DOCS
   url: /docs/getting-started/index.html
   context: /docs/

defaults:
  -   
   scope:
     type: pages
   values:
     permalink: /:path/:basename:output_ext
  -   
   scope:
     type: posts
   values:
     permalink: /blog/:year-:month-:day-:title.html

excerpt_separator: <!--more-->


authors:
  team:
    name: The Team
    web: /about
  ibodrov:
    name: Ivan Bodrov
    web: http://devtools.walmart.com/about-us.html#ibodrov
  jvanzyl:
    name: Jason van Zyl
    web: http://devtools.walmart.com/about-us.html#jvanzyl
  mmoser:
    name: Manfred Moser
    web: http://devtools.walmart.com/about-us.html#mmoser

   
# -------
# Jekyll 
# -------
markdown: kramdown
kramdown: 
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false

exclude: 
  - "*.sh"
  - "wmt-release*"



