flows:
  main:
  - smtp: [ "${execution}", "${smtpServer}", {
      from: "${sender}",
      to: "${recipient}",
      subject: "Howdy",
      template: "mail.mustache"
    }]
  - log: mail sent to ${recipient}

variables:
  dependencies: [
    "http://nexus.prod.walmart.com/nexus/service/local/repo_groups/devtools-public/content/com/walmartlabs/concord/plugins/smtp-tasks/0.6.0/smtp-tasks-0.6.0.jar"
  ]
  arguments:
    smtpServer:
      host: "localhost"
      port: 25
    sender: "me@localhost"
    recipient: "you@localhost"
